# Generated by Django 4.2.16 on 2024-12-16 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit', models.CharField(db_index=True, max_length=255)),
                ('is_new', models.BooleanField(blank=True, db_index=True, default=True)),
                ('is_reviewed', models.BooleanField(blank=True, db_index=True, default=False)),
                ('is_fp', models.BooleanField(blank=True, db_index=True, default=False)),
                ('is_ignored', models.BooleanField(blank=True, db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('has_alerted', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=255)),
                ('tolerance', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 17, 2, 5, 48, 659450, tzinfo=datetime.timezone.utc), null=True)),
                ('last_ran', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 17, 2, 5, 48, 659918, tzinfo=datetime.timezone.utc), null=True)),
                ('update_interval', models.IntegerField(blank=True, db_index=True, default=1440, null=True)),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True)),
                ('last_completed', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 17, 2, 5, 48, 659970, tzinfo=datetime.timezone.utc), null=True)),
                ('is_approved', models.BooleanField(blank=True, db_index=True, default=True)),
                ('method', models.CharField(choices=[('regex', 'regex'), ('substring', 'substring'), ('strdistance', 'strdistance')], max_length=20)),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
            },
        ),
        migrations.CreateModel(
            name='STRrecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permit_number', models.CharField(blank=True, null=True)),
                ('address', models.CharField(blank=True, null=True)),
                ('permit_type', models.CharField(blank=True, null=True)),
                ('residential_subtype', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('expired', models.CharField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('bedroom_limit', models.CharField(blank=True, null=True)),
                ('guest_limit', models.CharField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, null=True)),
                ('operator_phone', models.CharField(blank=True, null=True)),
                ('operator_email', models.CharField(blank=True, null=True)),
                ('operator_permit_number', models.CharField(blank=True, null=True)),
                ('license_holder_name', models.CharField(blank=True, null=True)),
                ('application_date', models.DateTimeField(blank=True, null=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('reference_code', models.CharField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
